---
title: "Biostatistics project - Group 25"
author: "Robbe Claeys, Tom Nissens, ..."
date: "`r Sys.Date()`"
output: html_document
---

# BASTA strawberry trial 2022
This project for the biostatistics course is based on the BASTA research (Biochar’s Added value) organised by ILVO, UHasselt and pcfruit.

Biochar is the residual product formed after pyrolysis of biomass and has currently no economic value. In this project researchers are interested to see if (1) Biochar can partly replace peat and (2) Biochar can be used to promote plant development and/or plant disease resistance of strawberry.

---

**Variables:**

- the type of growing medium (peat, peat_biochar, peatfree, peatfree_biochar)
- the addition of biochar as a vaccine (vaccine 1-3)
- the addition of *Trichoderma* (Trichoderma 1-3)

There were a total of 28 growing blends (4 x 3 x 3 + 4 controls). For each blend three plant trays were filled, each containing five strawberry plants, and replicated four times. The trays were divided over two greenhouses (greenhouse 1-2)

**Measurements:**

- root rot score (30, 50, and 80 days after infection)
- total number of fruits over 15 plants
- number of fruits infected with *Botrytis* (after harvest, one week storage at 6°C, and three days storage at 20°C)
- weight of strawberries per plant in kg (class 1, class 2, curved, and total strawberries)
- fresh biomass per plant
- dry biomass per plant

**Research question:**  
On average, is there an effect of growing medium and/or the addition of Trichoderma on the weight of the curved strawberries. (data set 2)

---

# Variables
**Response variable(s):**

**Explanatory variable(s):**

**Observational unit (is this the same for each response variable?):**

**Experimental unit (is this the same for each response variable?):**

# Hypotheses
Indicate all null & alternative hypotheses for your research question.

# Data exploration
Explore your data with some illustrative graphs and tables. What can you see on those? Are there already some trends appearing? Make all graphs through the package ggplot and try to make them as illustrative and attractive as possible.

```{r results = 'hide'}
data <- read.delim("data/BASTA_Dataset2_Trichoderma.txt", header = TRUE, stringsAsFactors = FALSE, quote = "", sep = "\t")
data
```


# Model selection and statisticial inference
Based on the data exploration and the type of data, which model will you use and are the assumptions fulfilled? What can you do to improve the model? Fit this model and do statistical testing with the best possible model from what you have learned in the course.

# Conclusion
Write an appropriate conclusion as if you would publish these results in a scientific journal.

The project needs to be handed in by Friday 23/12. Hand in an HTML file containing all your code + conclusions. The file should be saved as ProjectBiostatistics_Member1_Member2_Member3_Member4.

